In [1]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True) #最重要的，告诉自动微分引擎开始追踪该变量
x.grad
y=2*torch.dot(x,x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()#手动清零
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y =3* x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([ 0.,  6., 12., 18.])

In [2]:
x.grad.zero_()
y = x * x
u = y.detach()#相当于创建一个副本，人为认定u与x,y无关
z = u * x
'''类似于偏微分'''
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [19]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)